use_frameworks!

platform :ios, '8.0'

target 'CCBRKValuePopUpView_Example' do
  pod 'CCBRKValuePopUpView', :path => '../'

  target 'CCBRKValuePopUpView_Tests' do
    inherit! :search_paths

    
  end
end
